##
##  Submit RecoSelection job to Condor
##

executable  = execReco.sh
universe    = vanilla

output      = reports/selected_$(suffix)_$INT(Step).out
error       = reports/selected_$(suffix)_$INT(Step).err
log         = reports/selected_$(suffix)_$INT(Step).log

should_transfer_files   = YES
initialdir              = output
transfer_input_files    = source.tar.gz
when_to_transfer_output = ON_EXIT

arguments   = "$(suffix) $INT(Step)"

    suffix = muon_2016
    queue 15

    suffix = electron_2016
    queue 8

    suffix = zjets_m-50
    queue 10

#   suffix = zjets_m-10
#   queue 1

#   suffix = ttbar
#   queue 1

#   suffix = tt_2l2nu
#   queue 6

#   suffix = ww_2l2nu
#   queue 1

#   suffix = wz_2l2q
#   queue 4

#   suffix = wz_3lnu
#   queue 1

#   suffix = zz_2l2nu
#   queue 10

#   suffix = zz_2l2q
#   queue 1

    suffix = zz_4l
    queue 2

#   suffix = ggH_zz_4l
#   queue 1

#   suffix = vbfH_zz_4l
#   queue 1
