##
##  Submit RecoSelection job to Condor
##

executable  = execSameSign.sh
universe    = vanilla

output      = reports/selected_$(suffix)_$INT(Step).out
error       = reports/selected_$(suffix)_$INT(Step).err
log         = reports/selected_$(suffix)_$INT(Step).log

should_transfer_files   = YES
initialdir              = output
transfer_input_files    = source.tar.gz
when_to_transfer_output = ON_EXIT

arguments   = "$(suffix) $INT(Step)"

#   suffix = muon_2016
#   queue 25

#   suffix = electron_2016
#   queue 15

    suffix = zjets_m-50
    queue 20
