##################################
# test
##################################
executable  = execSelection.sh
universe    = vanilla


output      = run_$(suffix)_$INT(Process).out
error       = run_$(suffix)_$INT(Process).err
log         = run.log


should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = ../macros/handleSelection.cc


arguments   = "$(suffix) $INT(Process)"
queue $INT(nFiles)
