##
##  Submit RecoSelection job to Condor
##

executable  = execSyst.sh
universe    = vanilla

output      = reports/smeared_$(systematics)_$(suffix)_$INT(Process).out
error       = reports/smeared_$(systematics)_$(suffix)_$INT(Process).err
log         = reports/smeared.log

should_transfer_files   = YES
initialdir              = output
transfer_input_files    = source.tar.gz
when_to_transfer_output = ON_EXIT

arguments   = "$(suffix) $INT(Process) $(systematics)"
queue $INT(nFiles)
