##
##  Submit RecoSelection job to Condor
##

executable  = execSyst.sh
universe    = vanilla

output      = reports/$(syst)$(disp)_$(suffix)_$INT(Step).out
error       = reports/$(syst)$(disp)_$(suffix)_$INT(Step).err
log         = reports/$(syst)$(disp)_$(suffix)_$INT(Step).log

should_transfer_files   = YES
initialdir              = output
transfer_input_files    = source.tar.gz
when_to_transfer_output = ON_EXIT

arguments   = "$(suffix) $INT(Step) $(syst) $(disp)"

    suffix = electron_2018

#       syst = electronPt

#           disp = Up
#           queue 15

#           disp = Down
#           queue 15

        syst = muonPt

            disp = Up
            queue 15

            disp = Down
            queue 15


    suffix = muon_2018

#       syst = electronPt

#           disp = Up
#           queue 25

#           disp = Down
#           queue 25

        syst = muonPt

            disp = Up
            queue 25

            disp = Down
            queue 25
