##
##  Submit RecoSelection job to Condor
##

executable  = execReco.sh
universe    = vanilla

output      = reports/selected_$(suffix)_$INT(Process).out
error       = reports/selected_$(suffix)_$INT(Process).err
log         = reports/selected.log

should_transfer_files   = YES
initialdir              = output
transfer_input_files    = source.tar.gz
when_to_transfer_output = ON_EXIT

arguments   = "$(suffix) $INT(Process)"
queue $INT(nFiles)
