##
##  Submit RecoSelection job to Condor
##

executable  = execReco.sh
universe    = vanilla

output      = reports/selected_$(suffix)_$INT(Step).out
error       = reports/selected_$(suffix)_$INT(Step).err
log         = reports/selected_$(suffix)_$INT(Step).log

should_transfer_files   = YES
initialdir              = output
transfer_input_files    = source.tar.gz
when_to_transfer_output = ON_EXIT

arguments   = "$(suffix) $INT(Step)"

#   suffix = muon_2017
#   queue 10

#   suffix = electron_2017
#   queue 6

#   suffix = zz_4l
#   queue 1

    suffix = zz_4l_aMC
    queue 2

#   suffix = zjets_m-50
#   queue 10

#   suffix = ttbar
#   queue 1

#   suffix = tt_2l2nu
#   queue 1

#   suffix = ttz_2l2nu
#   queue 1

#   suffix = ww_2l2nu
#   queue 1

#   suffix = wz_2l2q
#   queue 2

#   suffix = wz_3lnu
#   queue 1

#   suffix = zz_2l2nu
#   queue 1

#   suffix = zz_2l2q
#   queue 2

#   suffix = ggH_zz_4l
#   queue 1

#   suffix = vbfH_zz_4l
#   queue 1

#   suffix = wwz_4l2nu
#   queue 1

#   suffix = wzz_4l2nu
#   queue 1

#   suffix = zzz_4l2nu
#   queue 1

#   suffix = zzg_4l2nu
#   queue 1
