##################################
# test
##################################
executable  = runHandler.sh
universe    = vanilla


id          = $(Process) + 1

output      = run_$(suffix)_$INT(id).out
error       = run_$(suffix)_$INT(id).err
log         = run.log


should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = handleSelection.cc, hzz_muon_id_sf.root, hzz_muon_id_smear.root 


arguments   = "$(selection) $(suffix) $INT(id)"
queue $INT(nFiles)
