ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MS,MDL_MU,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA
     $ ,MDL_MC,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MMU

      COMMON/MASSES/ MDL_MS,MDL_MU,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MC
     $ ,MDL_MB,MDL_ME,MDL_MD,MDL_MH,MDL_MMU


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_1, GC_2, GC_3, GC_74, GC_75, GC_76, GC_78,
     $  GC_79, GC_80, GC_100, GC_105, GC_108, GC_113, GC_118, GC_121,
     $  GC_132

      COMMON/COUPLINGS/ GC_1, GC_2, GC_3, GC_74, GC_75, GC_76, GC_78,
     $  GC_79, GC_80, GC_100, GC_105, GC_108, GC_113, GC_118, GC_121,
     $  GC_132

