ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of StandardModel'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_74 = ', GC_74
      WRITE(*,2) 'GC_75 = ', GC_75
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_100 = ', GC_100
      WRITE(*,2) 'GC_105 = ', GC_105
      WRITE(*,2) 'GC_108 = ', GC_108
      WRITE(*,2) 'GC_118 = ', GC_118
      WRITE(*,2) 'GC_121 = ', GC_121
      WRITE(*,2) 'GC_132 = ', GC_132
