ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of StandardModel'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_100 = ', GC_100
      WRITE(*,2) 'GC_113 = ', GC_113
      WRITE(*,2) 'GC_118 = ', GC_118
