ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of VectorU'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_82 = ', GC_82
      WRITE(*,2) 'GC_14 = ', GC_14
