ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of ScalarU'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_82 = ', GC_82
      WRITE(*,2) 'GC_102 = ', GC_102
      WRITE(*,2) 'GC_105 = ', GC_105
      WRITE(*,2) 'GC_108 = ', GC_108
      WRITE(*,2) 'GC_112 = ', GC_112
      WRITE(*,2) 'GC_116 = ', GC_116
      WRITE(*,2) 'GC_118 = ', GC_118
      WRITE(*,2) 'GC_125 = ', GC_125
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_14 = ', GC_14
